---
title: "Setup"
format: html
editor: visual
---

## Packages

```{r message=FALSE, warning=FALSE}
#|: installing-pkgs

# install.packages("tidyverse")
# install.packages("tidymodels")
# install.packages("writexl")
# install.packages("readxl")
# install.packages("lubridate")
# install.packages("wbstats") # for country GDP and total-export stats from World Bank
# install.packages("reticulate") # for running python stuff
# install.packages("tempdisagg") # for freq conv
# install.packages("tsbox") # for time-series visualizations
# install.packages("zoo") # also for freq conv
# install.packages("Hmisc") # date manipulations 
# install.packages("plyr")
# install.packages("hrbrthemes")
# install.packages("readr")
# install.packages("rvest")
# install.packages("httr")
# install.packages("xml2")
# install.packages("anytime")
```

```{r message=FALSE, warning=FALSE}
#|: loading-pkgs

library(tidyverse) 
library(tidymodels)
library(writexl)
library(readxl)
library(lubridate)
library(wbstats)
library(reticulate)
library(tempdisagg) 
library(tsbox) 
library(zoo)
library(Hmisc)
library(data.table)
library(plyr)
library(hrbrthemes)
library(readr)
library(rvest)
library(httr)
library(xml2)
library(anytime)
```

## Virtual Environment

```{r message = FALSE} <-}
#|: creating-virtual-env-and-installing-python-pkgs

virtualenv_create("my_environment")
Sys.setenv(RETICULATE_PYTHON = virtualenv_python("my_environment"))
# use_python(virtualenv_python("my_environment")) # line for Yue
use_virtualenv("my_environment")
virtualenv_install(
  "my_environment",
  c("export_ease", "comtradeapicall", "pandas", "requests", "flatten_json", "selenium", "webdriver_manager", "yfinance")
)
# py_config() # checking currently used Python version
source_python("scrape.py")
source_python("yfin.py")

virtualenv_python("my_environment")
```
